services:
  micronaut:
    container_name: micronaut
    image: a002k/micronaut:latest
    environment:
      - APP_NAME=${APP_NAME:-Micronaut}
    volumes:
      - micronaut:/home/app/data
    networks:
      - bridge-net

networks:
  bridge-net:
    driver: bridge

volumes:
  micronaut: